version: "3.9"

services:
  backend:
    build:
      context: ./twygo-api
      dockerfile: development.Dockerfile
    working_dir: /var/app
    ports:
      - "3001:3000"
    environment:
      - RAILS_ENV=development
    volumes:
      - ./twygo-api:/var/app 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      VITE_BACKEND_URL: "http://backend:3000"


